name: "Jellyfin Media Server"
description: >
  Jellyfin is a Free Software Media System that puts you in control of managing and streaming your media. 
  It is an alternative to the proprietary Emby and Plex, to provide media from a dedicated server to end-user devices via multiple apps. 
version: "10.9.7"
slug: jellyfin-media-server
# stage: stable
stage: experimental
advanced: true
url: https://hub.docker.com/r/linuxserver/jellyfin
init: false
arch:
  - amd64
  - aarch64
environment:
  PUID: "1000"
  PGID: "1000"
  TZ: Etc/UTC
ports:
  8096/tcp: 8096
  8920/tcp: 8920
  7359/udp: 7359
  1900/udp: 1900
ingress: true
ingress_port: 8096
usb: true
map:
  - addon_config:rw
  # - config:rw
  - media:rw
  # - downloads:rw
# password: 6QqCkDReY
